import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";
import Hero from "@/components/Hero";
import MiniNav from "@/components/MiniNav";
import Features from "@/components/Features";
import Categories from "@/components/Categories";
import Market from "@/components/Market";
export default function Home() {
  return (
    <>
      <Head>
        <title>Pizza bakery point, Patna - Order Online</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <main>
        <Nav />
        <MiniNav />
        <Hero />
        <Features />
        <Categories />
        <Market />
      </main>
    </>
  );
}
